FROM python:3.9-slim

WORKDIR /usr/dashboardsapp/

COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . ./

CMD ["python3", "./run.py"]
# CMD gunicorn -b 0.0.0.0:80 run:server